name: Shell Commands

on: [issues]

jobs:                               # This workflow contains a single job called "build"
  run-shell-command:                # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:

    - name: echo a string
      run: echo "Hello World"

    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        pwd
        ls -ahl
        node -v
        npm -v
        
